### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by rdrunner74** [li-xinyang/OS_FrontendMaster-dl#63] opened 2018-01-20 18:53 UTC
Trying to download good-parts-javascript-web (https://frontendmasters.com/courses/good-parts-javascript-web/)
I am running this: 
```
python frontendmasters-dl.py --mute-audio --id USERNAME --password PASSWORD --course good-parts-javascript-web
```
This is a big course (I think there is a timeout problem), It works for other smaller courses.
It appears that the signature and expire parameters expire by the time the app starts to download the links.
The download fails at the download section with the following error:

Downloading: Two_Systems
Traceback (most recent call last):
```
  File "frontendmasters-dl.py", line 24, in <module>
    downloader()
  File "c:\python27\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 17, in downloader
    spider.download(course, high_resolution, video_per_video)
  File "C:\OS_FrontendMaster-dl-master\extractor\spider.py", line 56, in download
    self.download_course(course_downloadbale)
  File "C:\OS_FrontendMaster-dl-master\extractor\spider.py", line 219, in download_course
    self.download_video(i1, i2, subsection, section_title, course_path)
  File "C:\OS_FrontendMaster-dl-master\extractor\spider.py", line 227, in download_video
    i1, i2, subsection, section_title, course_path
  File "C:\OS_FrontendMaster-dl-master\extractor\helper.py", line 16, in get_local_file_path
    extension = get_file_path_from_url(subsection['downloadable_url'])
  File "C:\OS_FrontendMaster-dl-master\extractor\helper.py", line 43, in get_file_path_from_url
    return url.split("?")[0].split(".")[-1]
AttributeError: 'NoneType' object has no attribute 'split'
```
Also get this error message:
`[0120/141913.667:WARNING:audio_sync_reader.cc(172)] ASR: No room in socket buffer.: The pipe is being closed. (0xE8)`

**Comment by vvscode** [comment] 2018-01-25 19:45
for me it works fine

**Comment by rdrunner74** [comment] 2018-01-25 21:23
For this course: good-parts-javascript-web?

**Comment by vvscode** [comment] 2018-02-05 19:12
yep

**Comment by lostdesign** [comment] 2018-02-21 12:31
No issues with other courses but this one: `css3-in-depth`
Everytime after the links have been collected and the download starts, it will crash.

```
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 24, in <module>
    downloader()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 17, in downloader
    spider.download(course, high_resolution, video_per_video)
  File "/Users/x/Documents/05_CODING/OS_FrontendMaster-dl/extractor/spider.py", line 56, in download
    self.download_course(course_downloadbale)
  File "/Users/x/Documents/05_CODING/OS_FrontendMaster-dl/extractor/spider.py", line 219, in download_course
    self.download_video(i1, i2, subsection, section_title, course_path)
  File "/Users/x/Documents/05_CODING/OS_FrontendMaster-dl/extractor/spider.py", line 227, in download_video
    i1, i2, subsection, section_title, course_path
  File "/Users/x/Documents/05_CODING/OS_FrontendMaster-dl/extractor/helper.py", line 16, in get_local_file_path
    extension = get_file_path_from_url(subsection['downloadable_url'])
  File "/Users/x/Documents/05_CODING/OS_FrontendMaster-dl/extractor/helper.py", line 43, in get_file_path_from_url
    return url.split("?")[0].split(".")[-1]
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by vahidm-sp** [comment] 2018-04-06 16:30
user ` --video-per-video` i tested it, it will fix the problem

**Comment by vahidm-sp** [comment] 2018-04-06 16:31
use ` --video-per-video` i tested it, it will fix the problem

**Comment by li-xinyang** [comment] 2018-04-17 04:17
Closing the ticket, please try the new version and reopen the ticket if the issue is still unsolved.

**Closed by li-xinyang** 2018-04-17 04:17 UTC
