### ISSUE TITLE
Scripts Fails on Windows 7

### ISSUE THREAD

**Issue by bhagatparwinder** [li-xinyang/OS_FrontendMaster-dl#6] opened 2017-02-23 18:15 UTC
Running

`python run.py`

throws error on Windows 7 with Python 2.7. Log below:

`[7184:7400:0223/121139.335:ERROR:configuration_policy_handler_list.cc(92)] Unknown policy: PasswordManagerAllowShowPasswords
[7184:7400:0223/121139.415:ERROR:configuration_policy_handler_list.cc(92)] Unknown policy: PasswordManagerAllowShowPasswords
[7184:14288:0223/121150.458:ERROR:ssl_client_socket_impl.cc(1101)] handshake failed; returned -1, SSL error code 1, net_error -101
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    browser_login()
  File "C:\Users\UserName\OS_FrontendMaster-dl\spider.py", line 34, in browser_login
    time.sleep(2)`

**Comment by bhagatparwinder** [comment] 2017-02-23 18:20
If it helps, it works flawlessly on macOS Sierra 10.12

**Comment by joshpitzalis** [comment] 2017-03-11 14:19
I'm on Sierra and it doesn't work for me either. 

@bhagatparwinder I downloaded the chrome driver, but what am I supposed to do with it once it's downloaded?

This the error I get when I run `python run.py`

<img width="1002" alt="screen shot 2017-03-11 at 19 47 53" src="https://cloud.githubusercontent.com/assets/10258114/23823961/c5a41bfc-0693-11e7-804e-d5eb8998a774.png">

**Comment by joshpitzalis** [comment] 2017-03-11 14:27
Figured it out. I needed to add the location of chromedriver into line 22 of spider.py. So if I kept chromedriver on the desktop then it needed to say `browser = webdriver.Chrome('/Users/josh/desktop/chromedriver')`

**Comment by andreiglingeanu** [comment] 2017-03-11 19:05
@joshpitzalis you wouldn't need to change `spider.py` if chromedriver will be in your `$PATH`

**Comment by bhagatparwinder** [comment] 2017-03-13 17:33
@andreiglingeanu +1 . It's better to have it in PATH

**Comment by joshpitzalis** [comment] 2017-03-15 09:57
how do I add it to my path?

**Comment by bhagatparwinder** [comment] 2017-03-16 20:52
@joshpitzalis Follow these:

> Open up Terminal
Run sudo nano /etc/paths
Enter your password
Go to the bottom of the file and enter the path you wish to add
My PATH looks like: /Users/name/Documents/WebDriver
Control-x to quit
Y to save
Press enter to confirm
To double check, quit Terminal and relaunch it. Run echo $PATH. You should see your newly added path in the stream of other paths already there.

[Source](http://www.kenst.com/2015/03/installing-chromedriver-on-mac-osx/)

**Comment by joshpitzalis** [comment] 2017-03-17 04:45
Thank you very much.

**Comment by bhagatparwinder** [comment] 2017-03-17 17:23
@li-xinyang The original issue is not yet resolved. @joshpitzalis had some other issue that I helped him with.

**Comment by li-xinyang** [comment] 2017-03-18 02:24
I do not have a Win machine cannot reproduce the issue, but I will reopen the issue and see other will continue encounter the same problem.

**Comment by gabrielnemeth** [comment] 2017-04-05 18:27
On windows 10 it's working fine.

**Comment by ukaric** [comment] 2017-04-18 10:32
@gabrielnemeth Hi Im having issues under Win10 Bash to make it work can you please share some info on how did you make it work.

**Comment by li-xinyang** [comment] 2017-04-18 11:58
The reason it does not work on Window is because the path is hard coded using Unix style.

**Comment by gabrielnemeth** [comment] 2017-04-18 12:10
@ukaric Hi, I'm using conemu, not win bash. Maybe it emulates unix path. Take a look. (https://conemu.github.io/)

**Comment by ukaric** [comment] 2017-04-18 13:18
@gabrielnemeth Thanks i will revert to it if i fail to make bash work nicely.

@li-xinyang Should work under Windows bash because it is fully fledged ubuntu 16.04 box, I didnt have problems with paths up until now. Maybe the issue is that I'm using wrong chromedriver i used linux_64 one and smylinked it because otherwise i had error yelling that it needs driver in $PATH.  Here is error that i get.
```
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 21, in <module>
    downloader()
  File "/home/kadza/.pyenv/versions/2.7.13/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/kadza/.pyenv/versions/2.7.13/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/kadza/.pyenv/versions/2.7.13/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kadza/.pyenv/versions/2.7.13/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 9, in downloader
    spider = Spider()
  File "/mnt/c/Users/uros/OS_FrontendMaster-dl/extractor/spider.py", line 22, in __init__
    self.browser = webdriver.Chrome()
  File "/home/kadza/.pyenv/versions/2.7.13/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/home/kadza/.pyenv/versions/2.7.13/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 96, in start
    self.assert_process_still_running()
  File "/home/kadza/.pyenv/versions/2.7.13/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service chromedriver unexpectedly exited. Status code was: 127
``` 
I even included win drivers but have not added them to $PATH here is the picture you may find it more helpful. 
![2017-04-18](https://cloud.githubusercontent.com/assets/9012882/25132572/45118d1a-244a-11e7-92b3-39564fb1314b.png)

**Comment by adrimonasterios** [comment] 2017-09-26 07:19
Hi, I'm using Bash in Windows and have a similar error...

>>> Login with your credential
>>> Downloading course: hapi-js
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 21, in <module>
    downloader()
  File "C:\users\Adri\AppData\Local\Programs\Python\Python36\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\users\Adri\AppData\Local\Programs\Python\Python36\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\users\Adri\AppData\Local\Programs\Python\Python36\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\users\Adri\AppData\Local\Programs\Python\Python36\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 14, in downloader
    spider.download(course)
  File "C:\Users\Adri\AppData\Local\Programs\Python\Python36\extractor\spider.py", line 37, in download
    course_detailed_list = self._get_detailed_course_list(course)
  File "C:\Users\Adri\AppData\Local\Programs\Python\Python36\extractor\spider.py", line 68, in _get_detailed_course_list
    sections = self._get_section_data(sections_items)
  File "C:\Users\Adri\AppData\Local\Programs\Python\Python36\extractor\spider.py", line 91, in _get_section_data
    videos_data = self._get_videos_data(videos_section_items)
  File "C:\Users\Adri\AppData\Local\Programs\Python\Python36\extractor\spider.py", line 116, in _get_videos_data
    course_subsection['title'] = format_filename(title)
NameError: name 'format_filename' is not defined

Any solutions yet?

**Comment by li-xinyang** [comment] 2017-11-30 05:48
We have updated the script and it is tested under Window 10. Close the issue and please try the latest version. Thank you.

**Closed by li-xinyang** 2017-11-30 05:48 UTC

**Comment by tranlehaiquan** [comment] 2017-12-10 04:03
@li-xinyang please update readme.md, thank you for support window 👍

**Comment by li-xinyang** [comment] 2017-12-10 09:14
@tranlehaiquan Done :)
