### ISSUE TITLE
AttributeError: 'module' object has no attribute '_base' ?

### ISSUE THREAD

**Issue by ztickm** [li-xinyang/OS_FrontendMaster-dl#64] opened 2018-01-29 20:45 UTC
Whenever I try to run the script e.g using `python frontendmasters-dl.py --help`
I get
```
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 2, in <module>
    from extractor.spider import Spider
  File "/home/mysername/somepath/OS_FrontendMaster-dl-master/extractor/spider.py", line 1, in <module>
    from bs4                             import BeautifulSoup
  File "/usr/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

```

**Comment by li-xinyang** [comment] 2018-01-29 20:51
```

**Comment by li-xinyang** [comment] 2018-04-17 04:17
Closing the ticket, please try the new version and reopen the ticket if the issue is still unsolved.

**Closed by li-xinyang** 2018-04-17 04:17 UTC
