### ISSUE TITLE
Node js version with chrome headless and puppeteer

### ISSUE THREAD

**Issue by sepiropht** [li-xinyang/OS_FrontendMaster-dl#60] opened 2018-01-06 02:53 UTC
I don't know if it is good place to share, but i'm working in similar tool in node js which I want to share with you. 
I build it with puppeter, i have many issues but it seems  so promising!!!
Sorry again for the issue but i really want to share and see if someone get interested.
[my repo](https://github.com/sepiropht/Frontend-Master-Downloader)

**Comment by li-xinyang** [comment] 2018-01-06 11:42
I think it is totally fine to share your script here. I will change the README to promote your script if it's more stable than this one.

**Comment by sepiropht** [comment] 2018-01-06 12:00
Ok thank. I didn't spot that  before but there is some place where i need to wait.
Sometimes even a message appear after too many request. 
I should have read your code sooner, you already solve this problems :)

**Comment by sepiropht** [comment] 2018-02-27 10:31
My package is now more stable  so it can be avaible with [npm](https://www.npmjs.com/package/frontend-master-downloader). Try it if you want, it have already some downloads

**Comment by li-xinyang** [comment] 2018-04-17 04:17
Closing the ticket, please try the new version and reopen the ticket if the issue is still unsolved.

**Closed by li-xinyang** 2018-04-17 04:17 UTC
